// Generated by ts-to-zod
import { z } from "zod";

const statusColorIdSchema = z.union([z.literal("amber"), z.literal("green"), z.literal("red"), z.literal("other")]);

const componentStatusIdSchema = z.union([z.literal("alpha"), z.literal("beta"), z.literal("generalAvailability"), z.literal("notApplicable"), z.literal("preAlpha"), z.literal("proposed"), z.literal("releaseCandidate"), z.literal("unavailable"), z.literal("underReview")]);

const componentTypeIdSchema = z.union([z.literal("app"), z.literal("connector"), z.literal("connectorConnection"), z.literal("context"), z.literal("contextModelGroup"), z.literal("contextModel"), z.literal("contextModelDimensionGroup"), z.literal("contextModelDimension"), z.literal("contextModelDimensionHierarchy"), z.literal("contextModelEntityGroup"), z.literal("contextModelEntity"), z.literal("contextModelEntityDataItem"), z.literal("contextModelEntityEvent"), z.literal("contextModelEntityPrimaryMeasure"), z.literal("contextModelSecondaryMeasureGroup"), z.literal("contextModelSecondaryMeasure"), z.literal("dataView"), z.literal("dimension"), z.literal("engine"), z.literal("eventQuery"), z.literal("presenter"), z.literal("presenterPresentation"), z.literal("tool")]);

const timestampSchema = z.number();

const componentStatusSchema = z.object({
    id: z.string(),
    color: statusColorIdSchema,
    label: z.string()
});

const componentRefSchema = z.object({
    id: z.string(),
    label: z.record(z.string(), z.string()),
    description: z.record(z.string(), z.string()),
    icon: z.string().optional(),
    iconDark: z.string().optional(),
    order: z.number(),
    path: z.string()
});

const componentConfigSchema = z.object({
    id: z.string(),
    label: z.record(z.string(), z.string()),
    description: z.record(z.string(), z.string()),
    firstCreatedAt: timestampSchema.optional(),
    icon: z.string().optional(),
    iconDark: z.string().optional(),
    lastUpdatedAt: timestampSchema.optional(),
    status: componentStatusSchema.optional(),
    statusId: componentStatusIdSchema,
    typeId: componentTypeIdSchema
});

const moduleTypeIdSchema = z.union([z.literal("app"), z.literal("engine"), z.literal("connector"), z.literal("context"), z.literal("presenter"), z.literal("tool")]);

const moduleConfigSchema = componentConfigSchema.extend({
    typeId: moduleTypeIdSchema,
    version: z.string()
});

const presenterOperationSchema = z.union([z.literal("list"), z.literal("render"), z.literal("setColorMode")]);

export const presenterConfigSchema = moduleConfigSchema.extend({
    presentations: z.array(componentRefSchema),
    operations: z.array(presenterOperationSchema),
    typeId: z.literal("presenter")
});
