// Generated by ts-to-zod
import { z } from 'zod';

const statusColorIdSchema = z.union([z.literal('amber'), z.literal('green'), z.literal('red'), z.literal('other')]);

const componentStatusIdSchema = z.union([
    z.literal('alpha'),
    z.literal('beta'),
    z.literal('generalAvailability'),
    z.literal('notApplicable'),
    z.literal('preAlpha'),
    z.literal('proposed'),
    z.literal('releaseCandidate'),
    z.literal('unavailable'),
    z.literal('underReview')
]);

const componentTypeIdSchema = z.union([
    z.literal('app'),
    z.literal('connector'),
    z.literal('connectorConnection'),
    z.literal('context'),
    z.literal('contextModelGroup'),
    z.literal('contextModel'),
    z.literal('contextModelDimensionGroup'),
    z.literal('contextModelDimension'),
    z.literal('contextModelDimensionHierarchy'),
    z.literal('contextModelEntityGroup'),
    z.literal('contextModelEntity'),
    z.literal('contextModelEntityDataItem'),
    z.literal('contextModelEntityEvent'),
    z.literal('contextModelEntityPrimaryMeasure'),
    z.literal('contextModelSecondaryMeasureGroup'),
    z.literal('contextModelSecondaryMeasure'),
    z.literal('dataView'),
    z.literal('dimension'),
    z.literal('engine'),
    z.literal('eventQuery'),
    z.literal('presenter'),
    z.literal('presenterPresentation'),
    z.literal('tool')
]);

const localeCodeSchema = z.union([z.literal('en-au'), z.literal('en-gb'), z.literal('en-us'), z.literal('es-es')]);

const localisedStringSchema = z.record(localeCodeSchema, z.string());

const componentStatusSchema = z.object({
    id: z.string(),
    color: statusColorIdSchema,
    label: z.string()
});

const componentConfigSchema = z.object({
    id: z.string(),
    label: z.record(z.string(), z.string()),
    description: z.record(z.string(), z.string()),
    firstCreatedAt: z.number().optional(),
    icon: z.string().optional(),
    iconDark: z.string().optional(),
    lastUpdatedAt: z.number().optional(),
    status: componentStatusSchema.nullable().optional(),
    statusId: componentStatusIdSchema,
    typeId: componentTypeIdSchema
});

const moduleTypeIdSchema = z.union([z.literal('app'), z.literal('engine'), z.literal('connector'), z.literal('context'), z.literal('presenter'), z.literal('tool')]);

const connectorCategorySchema = z.object({
    id: z.string(),
    label: z.string()
});

export const connectorImplementationSchema = z.object({
    activeConnectionCount: z.number().optional(),
    canDescribe: z.boolean().optional(),
    id: z.string().optional(),
    authMethodId: z.union([z.literal('apiKey'), z.literal('disabled'), z.literal('oAuth2'), z.literal('none')]),
    label: localisedStringSchema.optional(),
    maxConnectionCount: z.number().optional(),
    params: z.array(z.record(z.string(), z.string())).optional()
});

const connectorModuleCategoryIdSchema = z.union([z.literal('application'), z.literal('curatedDataset'), z.literal('database'), z.literal('fileStore')]);

const connectorOperationSchema = z.union([
    z.literal('abortOperation'),
    z.literal('authenticateConnection'),
    z.literal('createObject'),
    z.literal('describeConnection'),
    z.literal('dropObject'),
    z.literal('findObject'),
    z.literal('getRecord'),
    z.literal('listNodes'),
    z.literal('previewObject'),
    z.literal('removeRecords'),
    z.literal('retrieveRecords'),
    z.literal('upsertRecords')
]);

const connectorUsageIdSchema = z.union([z.literal('bidirectional'), z.literal('destination'), z.literal('source'), z.literal('unknown')]);

const moduleConfigSchema = componentConfigSchema.extend({
    typeId: moduleTypeIdSchema,
    version: z.string()
});

export const connectorConfigSchema = moduleConfigSchema.extend({
    category: connectorCategorySchema.optional(),
    categoryId: connectorModuleCategoryIdSchema,
    implementations: z.record(z.string(), connectorImplementationSchema),
    operations: z.array(connectorOperationSchema),
    typeId: z.literal('connector'),
    usageId: connectorUsageIdSchema,
    vendorAccountURL: z.string().nullable().optional(),
    vendorDocumentationURL: z.string().nullable().optional(),
    vendorHomeURL: z.string().nullable().optional()
});
